apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: git-provider
rules:
  - apiGroups: ["git.krateo.io"]
    resources: ["repoes"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

  - apiGroups: ["git.krateo.io"]
    resources: ["repoes/status"]
    verbs: ["get", "patch", "update"]

  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: git-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: git-provider
subjects:
- kind: ServiceAccount
  name: git-provider
  namespace: demo-system