apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: test-repo
spec:
  enableUpdate: false
  configMapKeyRef:
    key: values
    name: filename-replace-values
    namespace: default
  fromRepo:
    authMethod: generic
    branch: main
    path: skeleton
    usernameRef:
      key: username
      name: git-username
      namespace: krateo-system
    secretRef:
      key: token
      name: gh-sec
      namespace: krateo-system
    url: https://github.com/matteogastaldello/fromRepo
  toRepo:
    authMethod: generic
    branch: test
    cloneFromBranch: main
    path: /
    secretRef:
      key: token
      name: gh-sec
      namespace: krateo-system
    usernameRef:
      key: username
      name: git-username
      namespace: krateo-system
    url: https://github.com/matteogastaldello/toRepo
  unsupportedCapabilities: true
