apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: git-azuredevops-branch-5
spec:
  enableUpdate: false
  configMapKeyRef:
    key: values
    name: filename-replace-values
    namespace: default
  fromRepo:
    authMethod: generic
    branch: main
    path: skeleton
    usernameRef:
      key: username
      name: git-username
      namespace: default
    secretRef:
      key: token
      name: git-secret
      namespace: default
    url: https://github.com/matteogastaldello/fromRepo
  toRepo:
    authMethod: generic
    branch: main
    cloneFromBranch: main
    path: /
    secretRef:
      key: token
      name: git-secret
      namespace: default
    usernameRef:
      key: username
      name: git-username
      namespace: default
    url: https://matteogastaldello-org@dev.azure.com/matteogastaldello-org/teamproject/_git/repo-generated
  unsupportedCapabilities: true
