apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: git-user
spec:
  configMapKeyRef:
    key: values
    name: test-push-cm
    namespace: default
  deletionPolicy: Orphan
  fromRepo:
    authMethod: generic
    branch: main
    path: /
    usernameRef:
      key: username
      name: github-username
      namespace: default
    secretRef:
      key: token
      name: github-auth
      namespace: default
    url: https://github.com/matteogastaldello/fromRepo
  toRepo:
    authMethod: generic
    branch: main
    cloneFromBranch: main
    path: /
    secretRef:
      key: token
      name: github-auth
      namespace: default
    usernameRef:
      key: username
      name: github-username
      namespace: default
    url: https://github.com/matteogastaldello/toRepo
  unsupportedCapabilities: true
