apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: git-azuredevops-branch-5
spec:
  enableUpdate: false
  configMapKeyRef:
    key: values
    name: filename-replace-values
    namespace: default
  deletionPolicy: Delete
  fromRepo:
    authMethod: generic
    branch: main
    path: skeleton/
    usernameRef:
      key: username
      name: gh-sella-user
      namespace: default
    secretRef:
      key: token
      name: sella
      namespace: default
    url: https://github.com/matteogastaldello/fromRepo
  toRepo:
    authMethod: generic
    branch: test-5
    # cloneFromBranch: 
    usernameRef:
      key: username
      name: gh-azure-user
      namespace: default
    secretRef:
      key: token
      name: azure-pwd
      namespace: default
    url: https://matteogastaldello-org@dev.azure.com/matteogastaldello-org/teamproject/_git/repo-generated
  unsupportedCapabilities: true
