apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: template-microservice
spec:
  unsupportedCapabilities: true
  configMapKeyRef:
    name: git-provider-demo-claim
    namespace: default
    key: json
  fromRepo:
    url: https://Kiratech-BancaSella@dev.azure.com/Kiratech-BancaSella/Test-Sella/_git/krateo-template-microservice
    authMethod: basic
    path: skeleton/spring01
    secretRef:
      name: azuredevops-endpoint
      namespace: default
      key: token
  toRepo:
    url: https://Kiratech-BancaSella@dev.azure.com/Kiratech-BancaSella/Krateo%20Provider%20Project%20n.1/_git/template-microservice-test-1
    branch: master
    authMethod: basic
    secretRef:
      name: azuredevops-endpoint
      namespace: default
      key: token
